services:
  chatgpt_reverse_proxy:
    image: chatgpt_reverse_proxy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatgpt_reverse_proxy
    restart: always
    ports:
      - "8000:8000"
      - "7900:7900"
    volumes:
      - ./tmp:/app/tmp
    environment:
      - VNC_NO_PASSWORD=1
      - user_data_dir=/app/tmp
